[package]
name = "opengl"
version = "0.8.0"
edition = "2024"
build = "build.rs"


[build-dependencies]
gl_generator = "0.14"

[dependencies]
numeracy = {git = "https://github.com/TheBookwyrms/numeracy.git"}
#matrices = {path = "../matrices"}