[package]
name = "render_context"
version = "0.8.0"
edition = "2024"
build = "build.rs"



[dependencies]
glfw = { version = "0.60", default-features = false, features = ["prebuilt-libs", "raw-window-handle-v0-6"]}
opengl = {path = "../opengl_abstractions"}
numeracy = {git = "https://github.com/TheBookwyrms/numeracy.git"}